In [3]:
import numpy as np
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / e_x.sum(axis=-1, keepdims=True)
sentence = "What are the symptoms of diabetes?"
tokens   = sentence.lower().replace("?","").split()
seq_len  = len(tokens)   
d_model  = 8             
d_k      = 4             
np.random.seed(42)
X = np.random.randn(seq_len, d_model)
W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_k)
Q = X @ W_Q
K = X @ W_K
V = X @ W_V
scores = Q @ K.T / np.sqrt(d_k)
attention_weights = softmax(scores)
output = attention_weights @ V
print("Tokens:", tokens)
print("\nRaw Attention Scores (Q·Kᵀ / √d_k):")
print(np.round(scores, 4))
print("\nAttention Weights (after softmax):")
print(np.round(attention_weights, 4))
print("\nSelf-Attention Output:")
print(np.round(output, 4))
print("\nPer-token attention distribution")
for i, tok in enumerate(tokens):
    top = np.argsort(attention_weights[i])[::-1][:3]
    print(f"{tok:12s} attends most to: " +
          ", ".join(f"{tokens[j]}({attention_weights[i,j]:.3f})" for j in top))

Tokens: ['what', 'are', 'the', 'symptoms', 'of', 'diabetes']

Raw Attention Scores (Q·Kᵀ / √d_k):
[[ -2.0043   0.1474  -9.2666  15.6364   0.9979   2.0712]
 [  5.6947  -6.3037   2.7615 -11.8566 -10.3943  -4.0602]
 [ -2.5428   6.5946   7.4384  -7.6844  17.1126   2.2492]
 [  4.8953  -6.3351  -4.5462   1.9827 -12.964   -3.0875]
 [  4.3386  -4.9768   1.1444  -6.5477 -10.4108  -3.2402]
 [  4.3229  -6.9946  -3.21    -0.4212 -16.4056  -3.4334]]

Attention Weights (after softmax):
[[0.000e+00 0.000e+00 0.000e+00 1.000e+00 0.000e+00 0.000e+00]
 [9.494e-01 0.000e+00 5.050e-02 0.000e+00 0.000e+00 1.000e-04]
 [0.000e+00 0.000e+00 1.000e-04 0.000e+00 9.999e-01 0.000e+00]
 [9.481e-01 0.000e+00 1.000e-04 5.150e-02 0.000e+00 3.000e-04]
 [9.600e-01 1.000e-04 3.940e-02 0.000e+00 0.000e+00 5.000e-04]
 [9.904e-01 0.000e+00 5.000e-04 8.600e-03 0.000e+00 4.000e-04]]

Self-Attention Output:
[[ 0.416   3.1783 -4.0227  1.9093]
 [ 0.492   4.0024 -0.1643 -3.6369]
 [ 3.1574 -2.5679  1.2379 -2.6127]
 [ 0.5942  4.55